namespace Application.DTOs.AI;

/// <summary>
/// Data Transfer Object for receiving responses from Gemini AI.
/// Contains the generated text and metadata about the response.
/// </summary>
public class GeminiResponseDto
{
    /// <summary>
    /// The text generated by Gemini AI in response to the prompt.
    /// </summary>
    public string Content { get; set; } = string.Empty;

    /// <summary>
    /// Indicates whether the request was successful.
    /// </summary>
    public bool IsSuccess { get; set; }

    /// <summary>
    /// Error message if the request failed.
    /// Null or empty if successful.
    /// </summary>
    public string? ErrorMessage { get; set; }

    /// <summary>
    /// Timestamp when the response was generated.
    /// </summary>
    public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Number of tokens used in the response (if available).
    /// </summary>
    public int? TokensUsed { get; set; }
}