using Application.DTOs.Employee;
using Application.Interfaces.PDF;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Infrastructure.Services.PDF;

public class PdfService : IPdfService
{
    public PdfService()
    {
        // License setup (Community License for QuestPDF)
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public byte[] GenerateEmployeeResume(EmployeeDto employee)
    {
        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.PageColor(Colors.White);
                page.DefaultTextStyle(x => x.FontSize(12));

                page.Header()
                    .Text($"Resume: {employee.FirstName} {employee.LastName}")
                    .SemiBold().FontSize(20).FontColor(Colors.Blue.Medium);

                page.Content()
                    .PaddingVertical(1, Unit.Centimetre)
                    .Column(x =>
                    {
                        x.Spacing(20);

                        x.Item().Text($"Position: {employee.Position}");
                        x.Item().Text($"Department: {employee.DepartmentName}");
                        x.Item().Text($"Email: {employee.Email}");
                        x.Item().Text($"Phone: {employee.Phone}");
                        x.Item().Text($"Hire Date: {employee.HireDate:yyyy-MM-dd}");
                        
                        x.Item().LineHorizontal(1).LineColor(Colors.Grey.Medium);
                        
                        x.Item().Text("Professional Details").Bold().FontSize(16);
                        x.Item().Text($"Salary: {employee.Salary:C}");
                        x.Item().Text($"Status: {employee.Status}");
                    });

                page.Footer()
                    .AlignCenter()
                    .Text(x =>
                    {
                        x.Span("Generated by Express Firmeza System - ");
                        x.CurrentPageNumber();
                    });
            });
        });

        return document.GeneratePdf();
    }
}
